### ISSUE TITLE
[TODO] Document linter workflow

### ISSUE THREAD

**Issue by ruestefa** [MeteoSwiss-APN/mch-python-blueprint#12]
- [ ] Add section on linter workflow to [readme/development_tools.rst](https://github.com/MeteoSwiss-APN/mch-python-blueprint/blob/master/readme/development_tools.rst}
  - How to interpret and fix errors raised by flake8, pylint, pydocstyle, mypy
  - Which errors to disable globally in [tox.ini](https://github.com/MeteoSwiss-APN/mch-python-blueprint/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/tox.ini) and which locally with directives (e.g., `# pylint: disable=XXXX`)
- [ ] Add case of migrating an existing project that did not use linter to the Blueprint
  - How to proceed when there are tons of errors:
    - Disable errors for the moment in [tox.ini](https://github.com/MeteoSwiss-APN/mch-python-blueprint/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/tox.ini)
    - Fix errors in the code and re-enable when linters satisfied
    - However, don't "naively" fix them one-by-one without knowing how the end result should roughly look (otherwise too many iterations in the same locations)

**Comment by ruestefa** [comment]
Merged #10 into this issue to close the former.

**Comment by regDaniel** [comment]
@ruestefa Would you consider this covered in the docs as they are now? If yes, we can close this one.

**Comment by ruestefa** [comment]
No, I wouldn't. The docs (`docs/development_tools.rst`) describe what tools are provided, what they do and how they are run, but not how they are actually used in practice during development. What I was aiming at here is some guidance on what kinds of errors typically to expect in previously unlinted code and how to best address them, i.e., what can be easily fixed, what can be best addressed with directives (`# pylint: ignore=...` etc.) in the code (only temporarily, of course, or so the wishful thinking goes...) and what errors are best disabled in `pyproject.toml`.

Regarding docstrings, there should be a short reference to the preferred docstring format(s) (e.g., google, numpy) and maybe some examples (though not too much; there are enough resources on the web). AFAIK, there's nothing in the docs on this currently.

Whether these things should be added to the blueprint, and if yes, at what level of detail, is of course up for debate. My suggestion would be to just keep the issue open with a "low priority" tag.

 While reading `docs/development_tools.rst`, I noticed a few things that should/could be improved:

- [ ] Remove references to `tox` (currently not part of the blueprint anymore).
- [ ] Streamline and shorten the descriptions of code formatters and pre-commit to the necessary (there are many detailed tutorials on the net).
- [ ] Reformulate the description of pre-commit slightly because now reads as if pre-commit were primarily a github actions thing that can also optionally be run locally at every commit if the developer really, really, really wants to, when in fact that should be enforced as much as possible (and for sure be the default). By default, `pre-commit install` should always be run first thing in a new repo.
- [ ] Document why most tools are run locally (`repo: local` & `language: system`) (reason: to pin their versions exactly once: in `environment.yml`).
- [ ] Pre-commit no longer comes with "several useful tools which are primarily aimed at code formatting", but also with several linters (mypy, flake8, pylint, pydocstyle), which are missing from the list.
- [ ] Update description of codespell, which is now run by pre-commit by default (and, in my experience, doesn't yield too many false positives [anymore?]).

**Comment by ruestefa** [comment]
@regDaniel I just created a blueprint-based project for someone and wanted to point her to the documentation of linters etc., when I noticed that it's in the root docs of the blueprint rather than in the docs of blueprint-derived packages. I'd strongly suggest to move it from the former to the latter (e.g., merge it into `CONTRIBUTING.md` or just move the file as is to `tmpl/docs/`) so it's also directly available to (especially new) users, many of which won't check (or even know about) the blueprint github pages with its docs. Do you agree, or is there a reason why it's done like this?

**Comment by regDaniel** [comment]
Hi @ruestefa yes, the reason is that we deploy the docs as html to [pages](https://meteoswiss-apn.github.io/mch-python-blueprint/index.html) a solution we found to be practical and quite neat. The section on linters is [here](https://meteoswiss-apn.github.io/mch-python-blueprint/development_tools.html).

**Comment by ruestefa** [comment]
OK, I see, never mind then.
