### ISSUE TITLE
towards v2

### ISSUE THREAD

**Issue by cosunae** [MeteoSwiss-APN/mch-python-blueprint#26]
### Description

- Install: use conda in jenkins environment, optionally the user can use mamba
 
Waterfall project description towards a v2. 

- [x] Add github actions and jenkins files to the templates [Carlos] [Stefan: #50]
- [x] Replace Makefile with github actions for precommit checkers [Carlos] [Stefan: Makefile removed in #48]
- [x] Replace makefile targets by python scripts for common actions: (#42)
  - [x] Install [D. Regenass] (#32) [Stefan] (#47)
  - [x] Update of pinned environmnent from unpinned environment. → we want to test this. [~Stefan~ D. Regenass] (#32, #47)
  - [x] Remove the bump version from the Makefile. We dont need the bumped version anymore since new releases of python is all integrated in a version in the setup.py. User is responsible for upgrading the version in setup.py and tagging accordingly. [D. Hupp] [Stefan: removed in #48]
- [x] For pre-commit format and linters we integrate them into the github actions. Additionally we add those lightweight as local hooks (all except pylint?) . Provide different pre-commit setups for local hooks (lightweight) and CI.  [Carlos]
- [ ] Document how to integrate all pre-commits and linters into VSCode. Investigate if it is possible to provide a VSCode template with configurations for all linters. [D. Hupp] (#41) (related: #48)
- [x] For testing, we setup a jenkins for PR (check before merge into master) and jenkins triggers also on every commit to master. Github actions for pre-commit (format & linters). Jenkins would invoke the tests in production env and within tox. Tox could runnning multiple python version (at least production and latest). We would like to test this with a real example before proceeding (check how robust the solution for the blueprint is). Github actions do not need to run pre-commit with tox. [testing of tox Stefan/Carlos]
- [x] Integrate a documentation example (hello world) with default templates/themes and generate html for pushing into github IO pages. [D. Regenass]
- [x] We retain the blueprint for generating the metadata but we keep it simple and reduce examples to only 1. [D. Regenass]
- [x] Clean up branches [???]
- [x] Move to copier [Stefan] (#31)

**Comment by ruestefa** [comment]
After looking into how to update projects after changes to the underlying template (blueprint), I propose to switch from cookiecutter (which doesn't have this capability) to copier (which does): #31

**Comment by ruestefa** [comment]
My minor comments on #32 to be addressed/discussed at some point:

- `.github/workflows/precommit.yml`:
  - L. 31+: Could be done in one line: `conda env create -n blueprint -f \{\{cookiecutter.project_slug\}\}/requirements/requirements.yml`
  - L. 37+: Could be done in two lines:

    ```bash
    conda env create -n dev_blueprint --yes --file ...
    conda env update -n dev_blueprint --yes --file ...
    ```

  - L. 39: Use `environment.yml` instead of `requirements.yml`
  - These points also apply elsewhere in this file and `{{cookiecutter.project_slug}}/.github/workflows/precommit.yml`
- `docs/projects_and_blueprint.rst`:
  - L. 48: `\`\`\`shell` (introduced by me) triggers github actions warning; is there a standard designation of code regions containing bash commands and their terminal output?
- `{{cookiecutter.project_slug}}/requirements/*environment.yml`:
  - L. 4: Make sure that the docs mention that the channel order specified in `*.yml` files is only respected during `conda env create`, but not remembered by the env for subsequent actions like `conda env export` (see [#33](https://github.com/MeteoSwiss-APN/mch-python-blueprint/issues/33), [#45](https://github.com/MeteoSwiss-APN/mch-python-blueprint/issues/45))
  - Does it make sense to provide a non-empty environment.yml in the blueprint, which will necessarily be out-of-date when a new project is created? I'd suggest to provide empty *environment.yml files and leave it to the user to pin their environment (they'll have to do so anyway once they add runtime dependencies to the project). (But I don't have particularly strong feelings about this.)
- `{{cookiecutter.project_slug}}/requirements/*requirements.yml`:
  - Pin minimum package versions
- `{{cookiecutter.project_slug}}/setup_env.sh`:
  - L. 20: Consider replacing w/ `if ${HELP}; then`

I'll merge it as soon as Jenkins gives the green light.

**Comment by ruestefa** [comment]
@cosunae Can this be closed?

**Comment by regDaniel** [comment]
The only thing missing here is the VS Code integration, which is not straightforward (we know by now). I'll open a separate issue for this.
