### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by ruestefa** [MeteoSwiss-APN/mch-python-blueprint#46]
There are too many branches, many or which are likely obsolete:

```console
$ git branch -r
  origin/HEAD -> origin/master
  origin/conda
  origin/cython
  origin/dev
  origin/dev_refactor
  origin/dev_refactor_add_cfgs
  origin/example-chain_calc
  origin/example-chain_calc_cython
  origin/gh-pages
  origin/installation
  origin/master
  origin/stefan-cleanup
  origin/stefan-conda
  origin/test
```

Clean them up!

### TODO

- [x] ~`actions-workflow`~
- [x] ~`cython`~
- [x] `dev`
- [x] ~`dev_refactor`~
- [x] ~`dev_refactor_add_cfgs`~
- [x] ~`example-chain_calc`~
- [x] ~`example-chain_calc_cython`~
- [x] ~`fix_copier_cmd`~
- [x] ~`fix_sphinx`~
- [x] `gh-pages`
- [x] ~`installation`~
- [x] ~`master`~ `main`
- [x] ~`release_020`~
- [x] ~`test`~

**Comment by ruestefa** [comment]
- Update `dev_refactor_add_cfgs` to `dev_refactor` after merge of #32 
- Remove outdated branches `example-chain_calc` and `example-chain_calc_cython

**Comment by ruestefa** [comment]
```shell
$ git branch -r
warning: ignoring broken ref refs/remotes/origin/HEAD
  origin/actions-workflow
  origin/copier0_base
  origin/copier1_port
  origin/copier2_j2
  origin/copier3_more_docs
  origin/copier3_refine
  origin/copier3_setup_env
  origin/copier3_stefan-review
  origin/dev
  origin/dev_refactor_add_cfgs
  origin/fix_copier_cmd
  origin/fix_sphinx
  origin/gh-pages
  origin/main
  origin/release_020
  origin/stefan-setup_env.sh
  origin/test
```

I guess these can be safely deleted:

- `origin/copier0_base`
- `origin/copier1_port`
- `origin/copier2_j2`
- `origin/copier3_more_docs`
- `origin/copier3_refine`
- `origin/copier3_setup_env`
- `origin/copier3_stefan-review`
- `origin/stefan-setup_env.sh`

What about these, though?

- `origin/actions-workflow`
- `origin/dev_refactor_add_cfgs`
- `origin/fix_copier_cmd`
- `origin/fix_sphinx`
- `origin/gh-pages`
- `origin/release_020`
- `origin/test`

**Comment by ruestefa** [comment]
FYI, I noticed that `dev` was out of date since `dev_refactor` had been merged directly into `main`, so I updated `dev`.

**Comment by regDaniel** [comment]
I cleaned up somewhat radically. `gh-pages` is used by GitHub pages for the deployment of the docs to our pages website, so we can't delete it. If you agree @ruestefa I'll close this one.
