### ISSUE TITLE
review of dev_refactor

### ISSUE THREAD

**Issue by cosunae** [MeteoSwiss-APN/mch-python-blueprint#61]
* Cookiecutter version used, if any:
last version of dev_refactor

### Documentation: 

- [x] add a note to the documentation to carefully review the license, by default your package will be pushed with a MIT license? --> included in #67  review pending

- [x]  Missing what to do with the created package, install it, test it, run precommit, etc. i.e. what is in the doc of the package itself but that is optional --> included in #67 and #69, reviews pending

- [x] Documentation is not building on the github actions because mdinclude is missing

### Installation and environment:

- [x]  In the following, the fact the environment is not named as passed by arg is not very intuitive, 

```
          bash setup_env.sh -n flying_circus -d
         conda activate flying_circus-dev
```

- [x]  in dev-requirements.yml Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.

- [x] Make copier fetch the template from HEAD by adding `--vcs-ref=HEAD` to all Github actions workflows and Jenkins pipelines. --> included in #71 (review pending)

### Jenkins

- [x]  the jenkinsfile of the project template is broken, did not follow the last changes of the install

### pre-commit 

- [x]  recover rstcheck --> included in #72 (review pending)

**Comment by regDaniel** [comment]
Hi @cosunae and @ruestefa I have two suggestions on this. a) I will try to rewrite the installation section in the template docs such that I can link them on GH pages and they make sense in that context. On top of that, I'll add a brief summary with link to GH pages.
b) We have to rewrite the jenkinsfile anyways as we agreed to only test production installations on Jenkins and the rest on the actions server. I can do that but we should briefly discuss how to do the review (which might be a bit cumbersome as in principle we should create a package and a Jenkins pipeline to test it).

**Comment by regDaniel** [comment]
I see that you already fixed the template jenkinsfile, thanks @cosunae! In that case I think we can treat step (b) with lower priority as I think what we do currently does no harm.

**Comment by cosunae** [comment]
thanks @regDaniel, 
I fixed this https://github.com/MeteoSwiss-APN/mch-python-blueprint/blob/dev_refactor/jenkins/Jenkinsfile
but the one of the template, https://github.com/MeteoSwiss-APN/mch-python-blueprint/tree/dev_refactor/tmpl/jenkins
we still need to test manually, as you said a bit cumbersome until we find a better solution

**Comment by cosunae** [comment]
I think this was completed
